library(gains)
library(dplyr)
library(irr)
library(caret)
library(e1071)

setwd("C:/Users/pc/Documents/R Project")

```{r}
dm<-read.csv("dm.csv")
```

```{r}
dm%>%mutate(Target=ifelse(AmountSpent>mean(AmountSpent),1,0))->dm
dm%>%select(-AmountSpent)->dm
```

```{r}
summary(dm)
```

#Minimal Data Preparation

```{r}
dm$History1<-ifelse(is.na(dm$History),"Missing",as.character(dm$History))
dm$History1<-as.factor(dm$History1)

summary(dm$History1)

dm$Children<-as.factor(dm$Children)
dm$Catalogs<-as.factor(dm$Catalogs)

dm<-dm[,-8]
```

#Splitting into test and training samples

```{r}
set.seed(200)
index<-sample(nrow(dm),0.70*nrow(dm),replace=F)
train<-dm[index,]
test<-dm[-index,]
```

```{r}
mod<-glm(Target~.,data=train[,-9],family="binomial")
```

```{r}
summary(mod)
```

```{r}
step(mod,direction="both")
```

```{r}
mod1<-glm(formula = Target ~ Age + Location + Salary + Children + Catalogs +  History1, family = "binomial", data = train)

summary(mod1)
```

#Creating Dummies

```{r}
train$AgeYoung_d<-ifelse(train$Age=="Young",1,0)

train$Hist.Mid_d<-ifelse(train$History1=="Medium",1,0)

train$Children2_d<-ifelse(train$Children=="2",1,0)

train$Children3_d<-ifelse(train$Children=="3",1,0)

test$AgeYoung_d<-ifelse(test$Age=="Young",1,0)

test$Hist.Mid_d<-ifelse(test$History1=="Medium",1,0)

test$Children2_d<-ifelse(test$Children=="2",1,0)

test$Children3_d<-ifelse(test$Children=="3",1,0)
```


```{r}
mod2<-glm(Target~AgeYoung_d+Location+Salary+Children3_d+Children2_d+Catalogs+Hist.Mid_d,data=train,family="binomial")

summary(mod2)
```

```{r}
pred<-predict(mod2,type="response",newdata=test)
head(pred)
```

```{r}
table(dm$Target)/nrow(dm)
```

```{r}
pred<-ifelse(pred>=0.399,1,0)
```

```{r}
kappa2(data.frame(test$Target,pred))
```

```{r}
confusionMatrix(pred,test$Target,positive="1")
```

#Gains Chart (Study from Vdo lecture)

```{r}
gains(test$Target,predict(mod2,type="response",newdata=test),groups = 10)
```

```{r}
test$prob<-predict(mod2,type="response",newdata=test)

quantile(test$prob,prob=c(0.10,0.20,0.30,0.40,0.50,0.60,0.70,0.80,0.90,1))
```

```{r}
targeted<-test[test$prob>0.732602471&test$prob<=0.999747759,"Cust_Id"]

targeted
```
targeted contains the customer ids which correspond to the observations that have top 30% probability scores.